[tool.poetry]
name = "jupyter-nix-kernel-bash"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.11"
ipykernel = "*"

[tool.poetry.dev-dependencies]
bash_kernel = "*"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
